### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by kalefranz** [gaqzi/ansible-ssh-config#9]
Do you mind adding a license to this repo? (http://choosealicense.com/ for example)

Some people are just sticklers sometimes about these things.

**Comment by gaqzi** [comment]
In all honestly I don't know how to license it, because I've copied code in from a project that uses LGPL and a project that uses the MIT license.

The part that I've written is as far as I'm concerned public domain, but I don't want to relicense the code from the other projects. Despite it being, as far as I know, allowed by MIT license.

Do you have a suggestion for how I should solve this? :)
